ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
