ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
