ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_cut.o
